import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { SiteHeader } from "@/components/navigation/site-header";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
   return (
      <>
         <SidebarProvider
            style={
               {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
               } as React.CSSProperties
            }
         >
            <AppSidebar variant="inset" />
            <SidebarInset>
               <SiteHeader />
               <div className="p-4">{children}</div>
            </SidebarInset>
         </SidebarProvider>
      </>
   );
}
